### ISSUE TITLE
Textual timestamp

### ISSUE THREAD

**Issue by balabla908** [thuml/AutoTimes#10]
Hi, could you please explain how the .pt files related to data_stamp in the dataset are generated? Is there any code available for generating these files?

**Comment by WenWeiTHU** [comment]
Thanks for your interest in using the position embedding from textual timestamps. Note that we have provided the embeddings of the given datasets in the download links, which are generated by LLaMA, suffixed by `{dataset_name}.pt`. If you want to generate the embeddings from your customized datasets, please refer to the following codes:

```
# preprocess timestamps to generate text embedding
python ./preprocess.py --gpu 0 --dataset ETTh1
```
