### ISSUE TITLE
关于data_provider的疑问

### ISSUE THREAD

**Issue by FrankHo-Hwc** [thuml/AutoTimes#12]
请问autotimes的data_provider与time-series-library的data_provider能通用吗？好像autotimes的是将各个变量依次输出而非跟ts-lib一样直接输出多个变量的数据。如能回答，非常感谢！

**Comment by WenWeiTHU** [comment]
long-term的数据集加载方式和tslib是一致的，autotimes将各个变量依次输出是用到了channel indepdence

**Comment by FrankHo-Hwc** [comment]
> long-term的数据集加载方式和tslib是一致的，autotimes将各个变量依次输出是用到了channel independence

好的，非常感谢
