### ISSUE TITLE
multi-gpu support

### ISSUE THREAD

**Issue by GritLs** [thuml/AutoTimes#13]
Thank you for your outstanding work on this project and for making it open source!

I would like to inquire if multi-GPU training is supported. I noticed a switch on line 78 of run.py that controls whether to use multi-GPU. However, when I set this option to true and rerun the script, the process seems to get stuck, and the terminal outputs the following message:

![image](https://github.com/user-attachments/assets/c5621d21-6f75-46aa-9fa9-fad5b81ebbd3)

Could you please assist me with this issue? Thank you!

**Comment by hvlgo** [comment]
Please provide the modified scripts, or you can refer to [this](https://github.com/thuml/AutoTimes/blob/main/scripts/time_series_forecasting/long_term/AutoTimes_Weather.sh). I guess it's most likely because use_multi_gpu was used, but torchrun wasn't used to start.
