### ISSUE TITLE
Are Language Models Actually Useful for Time Series Forecasting？

### ISSUE THREAD

**Issue by nightforwar** [thuml/AutoTimes#14]
Hello! I recently read the article Are Language Models Actually Useful for Time Series Forecasting. I also noticed that your experiments included ablation studies from this paper, which demonstrated that your LLM is effective. Could you please explain why the LLM is effective in your architecture? Thank you for your response!

**Comment by WenWeiTHU** [comment]
Hello, thank you for your interest in our work. In response to your question, we think the main difference of AutoTimes from previous work is the  consistency of **causality** and **autoregression**. We have recently provided a [detailed PPT](https://cloud.tsinghua.edu.cn/f/7689d30f92594ded84f0/) to illustrate it, and some relevant slides are as follows. If you have more questions, feel free to join the discussion!

<img width="962" alt="image" src="https://github.com/user-attachments/assets/95e1a0d9-a602-4754-a430-091949f2fbb9">


<img width="960" alt="image" src="https://github.com/user-attachments/assets/24775ccb-930e-41e5-b465-351c99cb7cd6">

**Comment by nightforwar** [comment]
Thanks！！
