### ISSUE TITLE
extension file .pt (preprocess.py)

### ISSUE THREAD

**Issue by m6129** [thuml/AutoTimes#3]
Hello,  Dear developers
Am I correct that the .pt file can only be obtained via llama model? 
Is it possible to get gov datasets translated into .pt format somewhere?
Thanks

[Tried to implement without llama on Kaggle but failed miserably](https://www.kaggle.com/mrantonzaitsev/autotimes)

**Comment by hvlgo** [comment]
The embeddings generated by small language models may not effectively capture their semantic information. Although it's possible to generate corresponding .pt files using GPT-2, the quality of GPT-2 embeddings is relatively low and may not necessarily provide significant help for predictions. If you're interested, you can give it a try. Additionally, you have two options: either remove the --mix_embeds parameter from the script and modify the dataloader to remove the code related to loading pt files, or use LLAMA for inference, with the corresponding preprocessed .pt files provided in the readme link.

**Comment by m6129** [comment]
Thanks. 
Maybe you have a ready archive with embedding-generated datasets ETTh1, ETTh2, ETTm1, ETTm2, weather, exchange_rate and illness?

**Comment by hvlgo** [comment]
Here are the .pt files of the relevant datasets extracted with llama 7b: [[Google Drive]](https://drive.google.com/file/d/1t7jOkctNJ0rt3VMwZaqmxSuA75TFEo96/view?usp=sharing)
[[Tsinghua Cloud]](https://cloud.tsinghua.edu.cn/f/849427d3926f4fabbee7/)

**Comment by m6129** [comment]
> Here are the .pt files of the relevant datasets extracted with llama 7b: [[Google Drive]](https://drive.google.com/file/d/1t7jOkctNJ0rt3VMwZaqmxSuA75TFEo96/view?usp=sharing) [[Tsinghua Cloud]](https://cloud.tsinghua.edu.cn/f/849427d3926f4fabbee7/)

Thanks. 
Too bad it's only ETTh1, weather.

**Comment by hvlgo** [comment]
You can easily obtain embeddings for other datasets through preprocess.py, all you need is an RTX 3090.

**Comment by m6129** [comment]
> You can easily obtain embeddings for other datasets through preprocess.py, all you need is an RTX 3090.

I don't have an RTX 3090, and I assume some people will run into this problem as well
