### ISSUE TITLE
Encountering Error When Running AutoTimes_M4.sh

### ISSUE THREAD

**Issue by shisi-cc** [thuml/AutoTimes#5]
When I run sh scripts/time_series_forecasting/short_term/AutoTimes_M4.sh, I encounter the following error. How can I resolve this?

> Traceback (most recent call last):
>   File "/data/work/TimeLLM/AutoTimes/run.py", line 124, in <module>
>     exp.train(setting)
>   File "/data/work/TimeLLM/AutoTimes/exp/exp_short_term_forecasting.py", line 60, in train
>     train_data, train_loader = self._get_data(flag='train')
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/work/TimeLLM/AutoTimes/exp/exp_short_term_forecasting.py", line 34, in _get_data
>     data_set, data_loader = data_provider(self.args, flag)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/work/TimeLLM/AutoTimes/data_provider/data_factory.py", line 32, in data_provider
>     data_set = Data(
>                ^^^^^
>   File "/data/work/TimeLLM/AutoTimes/data_provider/data_loader.py", line 247, in __init__
>     self.__read_data__()
>   File "/data/work/TimeLLM/AutoTimes/data_provider/data_loader.py", line 255, in __read_data__
>     training_values = np.array(
>                       ^^^^^^^^^
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (414,) + inhomogeneous part.

**Comment by hvlgo** [comment]
We implemented our repository based on [time-series-library](https://github.com/thuml/Time-Series-Library). You can refer to [this](https://github.com/thuml/Time-Series-Library/issues/381) to solve this problem.
