### ISSUE TITLE
Does AutoTimes support llama3 or any latest model?

### ISSUE THREAD

**Issue by forhonourlx** [thuml/AutoTimes#6]
Hi,
Does AutoTimes support llama3 or any latest model?
How's the workload of adapting to a new model?
Thank you for your great job.

**Comment by forhonourlx** [comment]
To be completely honest, the innovation, effectiveness, efficiency, and flexibility of this project are truly impressive. 
- In terms of innovation, the idea of frozen parameters and  training new embedding and projection layer is excellent. 
- Regarding effectiveness, it has achieved many benchmark successes and supports multiple variable prediction. 
- In terms of efficiency, there are many beneficial handles and designs. 
- As for ﻿flexibility, I randomly downloaded a llama3 fine-tuning model, and it ran through successfully. **It means that this framework no longer requires excessive concern about ﻿foundational LLM obsolescence over time and can fully utilize the latest foundational LLM for upgrades.** The last point, in particular, is exceptionally powerful, far surpassing the idea of creating a domain-specific model alone. 
Special thanks for your great work, which should be valuable to both academia and industry. However, it is unfortunate that the GitHub stars do not seem to adequately reflect your work. From a perspective of ﻿widespread dissemination, the name 'AutoTimes' is too common and lacks the characteristics of the LLM AI era, making it difficult to be searched or focused on. I am looking forward to your updates or new projects and would suggest you consider a name change for the new project or self-recommend the project to the relevant new medias. Finally, if the new project ﻿has been added some just out-of-the-box wrappers, or packaging it to PyPI, that would be appreciated indeed.
@WenWeiTHU

**Comment by WenWeiTHU** [comment]
Thanks for your concern and recognition so much!  We are very glad to hear about the compatibility of our framework on ever larger LLMs (such as llama3). Your suggestions about the name and out-of-box project is greatly appreciated. We will continue to improve this repo and look forward to any chance to apply the method into real-world practice.
