### ISSUE TITLE
请问AutoTimes训练完成后，如何部署？

### ISSUE THREAD

**Issue by jacks-tang** [thuml/AutoTimes#8]

**Comment by WenWeiTHU** [comment]
您好，AutoTimes训练时冻结了LLM的参数，训练完毕后只需要将原本LLM的第一层Embedding和最后一层的Projection替换为AutoTimes引入的层即可

<img width="1125" alt="image" src="https://github.com/thuml/AutoTimes/assets/39073236/d6a3a8b3-2787-427a-b80e-7a1bc71fe902">

**Comment by jacks-tang** [comment]
谢谢您的回复
